import { useState, useCallback, useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet';
import {
  Search,
  FileText,
  Users,
  ArrowRight,
  Building2,
  MapPin,
  Briefcase,
  Download,
  ChevronDown,
  FileType,
  Copy,
  CheckCircle2,
  Plus,
  Save,
  History,
  Loader2,
  Sparkles,
} from 'lucide-react';
import { toast } from 'sonner';
import { useClarvidaAuth } from '@/context/ClarvidaAuthContext';
import { ClarvidaNavHeader } from '@/components/clarvida/ClarvidaNavHeader';
import { ContextBuilder } from '@/components/clarvida/ContextBuilder';
import { BooleanSearchPanel } from '@/components/clarvida/BooleanSearchPanel';
import { useWorkflowRun } from '@/components/clarvida/ContextBuilder/useWorkflowRun';
import { WorkflowHistoryPanel } from '@/components/clarvida/ContextBuilder/WorkflowHistoryPanel';
import { useWorkflowHistory, WorkflowHistoryItem } from '@/hooks/useWorkflowHistory';
import MinimalSearchForm from '@/components/MinimalSearchForm';
import { ClarvidaJobTemplate } from '@/types/organization';
import { JobDescriptionExporter } from '@/utils/jobDescriptionExport';
import { ContentMockupRenderer, GeneratedContent } from '@/components/content/mockups';

const ClarvidaSourcing = () => {
  const { session, organization, userRole, user } = useClarvidaAuth();
  const [searchParams] = useSearchParams();
  const [activeTab, setActiveTab] = useState('builder');
  const [isExporting, setIsExporting] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);

  // Multi-content type state
  const [generatedContent, setGeneratedContent] = useState<GeneratedContent | null>(null);
  const [activeContentType, setActiveContentType] = useState<string>('Job Description');

  // Use the new workflow hook for session-scoped state
  const {
    runId,
    generatedDescription,
    jobTemplate: currentTemplate,
    booleanState,
    setGeneratedDescription: updateDescription,
    startNewRun,
    rerollBoolean,
    setBooleanVariant,
    restoreFromHistory,
    restoreFromSavedWorkflow,
    canGenerateBoolean,
    _rawState: workflowState,
  } = useWorkflowRun({ autoGenerateBoolean: true });

  // Workflow history persistence
  const {
    saveWorkflow,
    saving: isSaving,
  } = useWorkflowHistory({
    userId: user?.uid,
    organizationId: organization?.id,
  });

  // Get search params from URL (passed from hero search)
  const initialKeyword = searchParams.get('keyword') || '';
  const initialLocation = searchParams.get('location') || '';

  const handleJobDescriptionGenerated = (description: string, template: ClarvidaJobTemplate) => {
    updateDescription(description, template);
    setActiveContentType('Job Description');
    setGeneratedContent(null); // Clear non-job-description content
    // Boolean search will be auto-generated by the workflow hook
    toast.success('Job description generated! Boolean search will be created automatically.');
  };

  // Handler for non-job-description content types
  const handleContentGenerated = useCallback((content: GeneratedContent, contentType: string) => {
    setGeneratedContent(content);
    setActiveContentType(contentType);
  }, []);

  const handleStartNewJob = () => {
    startNewRun();
    setActiveTab('builder');
  };

  const handleSaveWorkflow = async () => {
    if (!workflowState) return;
    await saveWorkflow(workflowState);
  };

  const handleRestoreWorkflow = (item: WorkflowHistoryItem) => {
    restoreFromSavedWorkflow({
      runId: item.runId,
      jobTitle: item.jobTitle,
      jobDepartment: item.jobDepartment,
      jobLocation: item.jobLocation,
      generatedDescription: item.generatedDescription,
      booleanSearchString: item.booleanSearchString,
      booleanVariant: item.booleanVariant,
      booleanExplanation: item.booleanExplanation,
      booleanHistory: item.booleanHistory,
    });
    setHistoryOpen(false);
    // If boolean exists, switch to search tab so user can immediately search
    if (item.booleanSearchString) {
      setActiveTab('search');
    }
  };

  // Auto-save with debounce: saves 10 seconds after last change when workflow has required data
  const autoSaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const lastAutoSaveRef = useRef<string | null>(null);

  useEffect(() => {
    // Only auto-save when we have both description and boolean
    if (!workflowState.generatedDescription || !workflowState.booleanState.current) return;
    if (!user?.uid || !organization?.id) return;
    if (workflowState.booleanState.isGenerating) return;

    // Skip if nothing changed since last auto-save
    const stateHash = `${workflowState.runId}:${workflowState.booleanState.current}:${workflowState.booleanState.history.length}`;
    if (stateHash === lastAutoSaveRef.current) return;

    if (autoSaveTimerRef.current) {
      clearTimeout(autoSaveTimerRef.current);
    }

    autoSaveTimerRef.current = setTimeout(async () => {
      try {
        await saveWorkflow(workflowState);
        lastAutoSaveRef.current = stateHash;
      } catch {
        // Silent failure for auto-save — user can still manual save
      }
    }, 10000); // 10 second debounce

    return () => {
      if (autoSaveTimerRef.current) clearTimeout(autoSaveTimerRef.current);
    };
  }, [workflowState.generatedDescription, workflowState.booleanState.current, workflowState.booleanState.history.length, workflowState.runId, user?.uid, organization?.id, saveWorkflow, workflowState]);

  const handleExport = async (format: 'docx' | 'pdf' | 'md' | 'txt') => {
    if (!currentTemplate) {
      toast.error('Generate a job description first');
      return;
    }
    setIsExporting(true);
    const toastId = toast.loading(`Exporting to ${format.toUpperCase()}...`);

    try {
      await JobDescriptionExporter.export(currentTemplate, format);
      toast.success(`Downloaded ${format.toUpperCase()} file!`, { id: toastId });
    } catch (error) {
      console.error('Export failed:', error);
      toast.error(`Failed to export ${format.toUpperCase()}`, { id: toastId });
    } finally {
      setIsExporting(false);
    }
  };

  const copyToClipboard = () => {
    if (!generatedDescription) {
      toast.error('Generate a job description first');
      return;
    }
    navigator.clipboard.writeText(generatedDescription);
    toast.success('Copied to clipboard!');
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Header */}
      <ClarvidaNavHeader />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Page Header */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-8">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold text-foreground">Candidate Sourcing</h1>
            <p className="text-muted-foreground mt-1">
              Build job descriptions and find qualified candidates
            </p>
          </div>
          <div className="flex items-center gap-3 mt-4 md:mt-0">
            {currentTemplate && (
              <div className="flex items-center gap-2 text-sm text-muted-foreground bg-white px-4 py-2 rounded-lg shadow-sm">
                <Briefcase className="w-4 h-4 text-clarvida-primary" />
                <span className="font-medium">{currentTemplate.job_title}</span>
                {currentTemplate.location?.city && (
                  <>
                    <span className="text-gray-400">|</span>
                    <MapPin className="w-4 h-4 text-clarvida-primary" />
                    <span>{currentTemplate.location.city}, {currentTemplate.location.state}</span>
                  </>
                )}
              </div>
            )}
            {/* Save Workflow button - only show when we have content */}
            {generatedDescription && booleanState.current && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleSaveWorkflow}
                disabled={isSaving}
                className="border-emerald-600 text-emerald-600 hover:bg-emerald-600 hover:text-white"
              >
                {isSaving ? (
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <Save className="w-4 h-4 mr-2" />
                )}
                Save
              </Button>
            )}

            {/* History Panel Trigger */}
            <Sheet open={historyOpen} onOpenChange={setHistoryOpen}>
              <SheetTrigger asChild>
                <Button
                  variant="outline"
                  size="sm"
                  className="border-gray-300 text-muted-foreground hover:bg-gray-100"
                >
                  <History className="w-4 h-4 mr-2" />
                  History
                </Button>
              </SheetTrigger>
              <SheetContent side="right" className="w-[400px] sm:w-[540px] p-0">
                <SheetHeader className="p-4 border-b">
                  <SheetTitle className="flex items-center gap-2">
                    <History className="w-5 h-5 text-clarvida-primary" />
                    Saved Workflows
                  </SheetTitle>
                </SheetHeader>
                <WorkflowHistoryPanel
                  onRestoreWorkflow={handleRestoreWorkflow}
                  className="border-0 shadow-none h-[calc(100vh-80px)]"
                />
              </SheetContent>
            </Sheet>

            {/* Start New Job button - clears all state */}
            <Button
              variant="outline"
              size="sm"
              onClick={handleStartNewJob}
              className="border-clarvida-primary text-clarvida-primary hover:bg-clarvida-primary hover:text-white"
            >
              <Plus className="w-4 h-4 mr-2" />
              New Job
            </Button>
          </div>
        </div>

        {/* Organization Badge */}
        {organization && (
          <div className="mb-6 p-4 bg-clarvida-primary/5 rounded-lg border border-clarvida-primary/20">
            <div className="flex items-center gap-3">
              <Building2 className="w-5 h-5 text-clarvida-primary" />
              <span className="font-medium text-clarvida-primary">{organization.name}</span>
              {userRole && (
                <Badge className="bg-clarvida-primary text-white">
                  {userRole.charAt(0).toUpperCase() + userRole.slice(1)}
                </Badge>
              )}
            </div>
          </div>
        )}

        {/* Workflow Steps - Simplified: Build → Search → Review */}
        <div className="flex flex-wrap items-center gap-2 md:gap-4 mb-8">
          <div
            className={`flex items-center gap-2 px-4 py-2 rounded-full cursor-pointer transition-colors ${
              activeTab === 'builder'
                ? 'bg-clarvida-primary text-white'
                : 'bg-white text-muted-foreground hover:bg-clarvida-primary/10 border border-gray-200'
            }`}
            onClick={() => setActiveTab('builder')}
          >
            <span className={`w-6 h-6 rounded-full flex items-center justify-center text-sm font-bold ${
              activeTab === 'builder' ? 'bg-white/20' : 'bg-clarvida-primary/10'
            }`}>
              1
            </span>
            <span className="font-medium hidden sm:inline">Build Job + Boolean</span>
            <span className="font-medium sm:hidden">Build</span>
            {booleanState.current && (
              <CheckCircle2 className="w-4 h-4 ml-1 text-emerald-400" />
            )}
          </div>
          <ArrowRight className="w-5 h-5 text-gray-400 hidden sm:block" />
          <div
            className={`flex items-center gap-2 px-4 py-2 rounded-full cursor-pointer transition-colors ${
              activeTab === 'search'
                ? 'bg-clarvida-primary text-white'
                : booleanState.current
                ? 'bg-white text-muted-foreground hover:bg-clarvida-primary/10 border border-gray-200'
                : 'bg-gray-100 text-gray-400 cursor-not-allowed'
            }`}
            onClick={() => booleanState.current && setActiveTab('search')}
          >
            <span className={`w-6 h-6 rounded-full flex items-center justify-center text-sm font-bold ${
              activeTab === 'search' ? 'bg-white/20' : 'bg-clarvida-primary/10'
            }`}>
              2
            </span>
            <span className="font-medium hidden sm:inline">Search Candidates</span>
            <span className="font-medium sm:hidden">Search</span>
          </div>
          <ArrowRight className="w-5 h-5 text-gray-400 hidden sm:block" />
          <div
            className={`flex items-center gap-2 px-4 py-2 rounded-full ${
              activeTab === 'results'
                ? 'bg-clarvida-primary text-white'
                : 'bg-gray-100 text-gray-400 border border-gray-200'
            }`}
          >
            <span className={`w-6 h-6 rounded-full flex items-center justify-center text-sm font-bold ${
              activeTab === 'results' ? 'bg-white/20' : 'bg-gray-200'
            }`}>
              3
            </span>
            <span className="font-medium hidden sm:inline">Review Candidates</span>
            <span className="font-medium sm:hidden">Review</span>
          </div>
        </div>

        {/* Main Content */}
        <div className="space-y-6">
          {activeTab === 'builder' && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-[calc(100vh-280px)] overflow-hidden">
              {/* Context Builder */}
              <ContextBuilder
                onJobDescriptionGenerated={handleJobDescriptionGenerated}
                onContentGenerated={handleContentGenerated}
              />

              {/* Preview Panel - Artifact Style */}
              <Card className={`shadow-sm transition-all h-full flex flex-col overflow-hidden ${
                (generatedDescription || generatedContent) ? 'border-emerald-300 bg-emerald-50/30' : 'border-gray-200'
              }`}>
                <CardHeader className={`border-b flex-shrink-0 ${
                  (generatedDescription || generatedContent)
                    ? 'bg-clarvida-primary text-white'
                    : 'bg-gray-50 border-gray-200'
                }`}>
                  <div className="flex items-center justify-between">
                    <CardTitle className={`flex items-center gap-2 ${
                      (generatedDescription || generatedContent) ? 'text-white' : 'text-clarvida-primary'
                    }`}>
                      {(generatedDescription || generatedContent) ? (
                        <CheckCircle2 className="w-5 h-5" />
                      ) : (
                        <Sparkles className="w-5 h-5" />
                      )}
                      {(generatedDescription || generatedContent)
                        ? `Generated ${activeContentType}`
                        : 'Content Preview'
                      }
                    </CardTitle>

                    {/* Action buttons - only show when job description exists */}
                    {generatedDescription && activeContentType === 'Job Description' && (
                      <div className="flex items-center gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={copyToClipboard}
                          className="text-white hover:bg-white/20"
                        >
                          <Copy className="w-4 h-4 mr-1" />
                          Copy
                        </Button>

                        {/* Export Dropdown */}
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button
                              variant="secondary"
                              size="sm"
                              disabled={isExporting}
                              className="bg-white text-emerald-700 hover:bg-emerald-50"
                            >
                              <Download className="w-4 h-4 mr-1" />
                              Export
                              <ChevronDown className="w-3 h-3 ml-1" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end" className="w-56">
                            <DropdownMenuLabel>Download As</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem onClick={() => handleExport('docx')} className="cursor-pointer">
                              <FileType className="w-4 h-4 mr-2 text-blue-600" />
                              <div className="flex flex-col">
                                <span className="font-medium">Word Document</span>
                                <span className="text-xs text-gray-500">.docx with formatting</span>
                              </div>
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => handleExport('pdf')} className="cursor-pointer">
                              <FileText className="w-4 h-4 mr-2 text-red-600" />
                              <div className="flex flex-col">
                                <span className="font-medium">PDF Document</span>
                                <span className="text-xs text-gray-500">.pdf with Clarvida branding</span>
                              </div>
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem onClick={() => handleExport('md')} className="cursor-pointer">
                              <FileText className="w-4 h-4 mr-2 text-purple-600" />
                              <div className="flex flex-col">
                                <span className="font-medium">Markdown</span>
                                <span className="text-xs text-gray-500">.md with headers</span>
                              </div>
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => handleExport('txt')} className="cursor-pointer">
                              <FileText className="w-4 h-4 mr-2 text-muted-foreground" />
                              <div className="flex flex-col">
                                <span className="font-medium">Plain Text</span>
                                <span className="text-xs text-gray-500">.txt simple format</span>
                              </div>
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>
                    )}
                  </div>
                  {generatedDescription && currentTemplate && activeContentType === 'Job Description' && (
                    <p className="text-emerald-100 text-sm mt-1">
                      {currentTemplate.job_title} • {currentTemplate.location?.city}, {currentTemplate.location?.state}
                    </p>
                  )}
                  {generatedContent && activeContentType !== 'Job Description' && (
                    <p className="text-emerald-100 text-sm mt-1">
                      {generatedContent.metadata?.jobTitle || 'Generated content ready'}
                    </p>
                  )}
                </CardHeader>
                <CardContent className="p-4 flex-1 min-h-0 overflow-y-auto">
                  {/* Job Description View */}
                  {activeContentType === 'Job Description' && generatedDescription ? (
                    <div className="prose prose-sm max-w-none h-full flex flex-col space-y-4">
                      {/* Editable Job Description */}
                      <div>
                        <h4 className="text-sm font-medium text-gray-700 mb-2">Job Description</h4>
                        <Textarea
                          value={generatedDescription}
                          onChange={(e) => {
                            // Note: This only updates the local display, full state is in workflow
                          }}
                          readOnly
                          className="min-h-[200px] max-h-[250px] font-mono text-sm border-emerald-200 bg-white focus:border-emerald-500 focus:ring-emerald-500 resize-none overflow-y-auto"
                          placeholder="Your generated job description will appear here..."
                        />
                      </div>

                      {/* Boolean Search Panel - Auto-generated after job description */}
                      <BooleanSearchPanel
                        booleanState={booleanState}
                        onReroll={rerollBoolean}
                        onSetVariant={setBooleanVariant}
                        onRestoreFromHistory={restoreFromHistory}
                        canGenerate={canGenerateBoolean}
                      />

                      {/* Proceed to Search button */}
                      {booleanState.current && (
                        <div className="pt-4 border-t border-emerald-200">
                          <Button
                            onClick={() => setActiveTab('search')}
                            className="w-full bg-clarvida-primary hover:bg-clarvida-primary/80"
                          >
                            <Search className="w-4 h-4 mr-2" />
                            Search for Candidates
                            <ArrowRight className="w-4 h-4 ml-2" />
                          </Button>
                        </div>
                      )}
                    </div>
                  ) : generatedContent && activeContentType !== 'Job Description' ? (
                    /* Content Mockup View for non-job-description types */
                    <div className="h-full">
                      <ContentMockupRenderer
                        contentType={activeContentType}
                        content={generatedContent}
                      />
                    </div>
                  ) : (
                    /* Empty State */
                    <div className="text-center py-16 text-gray-500">
                      <Sparkles className="w-16 h-16 mx-auto mb-4 text-gray-300" />
                      <p className="text-lg font-medium mb-2">Ready to Generate Content</p>
                      <p className="text-sm">Select a content type and click "Generate" to create your content</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          )}

          {activeTab === 'search' && (
            <div className="space-y-6">
              {/* Current Job Context */}
              {currentTemplate && (
                <Card className="bg-clarvida-primary/5 border-clarvida-primary/20">
                  <CardContent className="p-4">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                      <div className="flex items-center gap-4">
                        <div className="p-3 bg-clarvida-primary rounded-lg">
                          <Briefcase className="w-6 h-6 text-white" />
                        </div>
                        <div>
                          <h3 className="font-semibold text-clarvida-primary">
                            {currentTemplate.job_title}
                            {currentTemplate.specialty_credential && ` – ${currentTemplate.specialty_credential}`}
                          </h3>
                          <p className="text-sm text-muted-foreground">
                            {currentTemplate.location?.city}, {currentTemplate.location?.state} |{' '}
                            {currentTemplate.employment_type} |{' '}
                            {currentTemplate.location?.work_arrangement}
                          </p>
                        </div>
                      </div>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setActiveTab('builder')}
                        className="border-clarvida-primary text-clarvida-primary hover:bg-clarvida-primary hover:text-white"
                      >
                        Edit Job
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Search Form with Job Description Context */}
              <MinimalSearchForm
                userId={session?.uid || null}
                selectedProjectId={null}
                isClarvidaMode={true}
                initialBooleanString={booleanState.current || undefined}
                initialJobTitle={currentTemplate?.job_title || undefined}
              />
            </div>
          )}

          {activeTab === 'results' && (
            <Card className="p-8 text-center border border-gray-200">
              <Users className="w-16 h-16 mx-auto mb-4 text-gray-300" />
              <h3 className="text-lg font-semibold text-gray-700 mb-2">Candidate Results</h3>
              <p className="text-gray-500">
                Complete the search step to see candidate results here
              </p>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
};

export default ClarvidaSourcing;
