// Apply Codes - Export utilities for candidate data
// Supports CSV download, clipboard copy, and shareable text

'use strict';

/**
 * Convert candidate records to CSV string.
 * @param {Object[]} candidates
 * @returns {string}
 */
function candidatesToCSV(candidates) {
  const headers = ['Name', 'Title/Headline', 'Company', 'Location', 'Profile URL', 'Skills', 'Source', 'Collected'];
  const rows = candidates.map(c => [
    escapeCSV(c.name),
    escapeCSV(c.headline),
    escapeCSV(c.company),
    escapeCSV(c.location),
    escapeCSV(c.profileUrl),
    escapeCSV((c.skills || []).join('; ')),
    escapeCSV(c.source),
    escapeCSV(formatDate(c.collectedAt)),
  ].join(','));

  return [headers.join(','), ...rows].join('\n');
}

/**
 * Convert candidate records to tab-separated values for clipboard pasting.
 * @param {Object[]} candidates
 * @returns {string}
 */
function candidatesToTSV(candidates) {
  const headers = ['Name', 'Title', 'Company', 'Location', 'Profile URL', 'Skills'];
  const rows = candidates.map(c => [
    c.name,
    c.headline,
    c.company,
    c.location,
    c.profileUrl,
    (c.skills || []).join('; '),
  ].join('\t'));

  return [headers.join('\t'), ...rows].join('\n');
}

/**
 * Generate a shareable plain-text summary.
 * @param {Object[]} candidates
 * @param {string} [criteria]
 * @returns {string}
 */
function candidatesToShareableText(candidates, criteria) {
  let text = `Candidate Sourcing Results\n`;
  text += `Generated by Apply Codes\n`;
  if (criteria) text += `Search: ${criteria}\n`;
  text += `Total: ${candidates.length} candidates\n`;
  text += `Date: ${new Date().toLocaleDateString()}\n`;
  text += `${'─'.repeat(50)}\n\n`;

  candidates.forEach((c, i) => {
    text += `${i + 1}. ${c.name}\n`;
    text += `   ${c.headline}\n`;
    if (c.company) text += `   Company: ${c.company}\n`;
    if (c.location) text += `   Location: ${c.location}\n`;
    text += `   ${c.profileUrl}\n\n`;
  });

  return text;
}

/**
 * Download a CSV file to the user's computer.
 * @param {Object[]} candidates
 * @param {string} [filename]
 */
function downloadCSV(candidates, filename) {
  const csv = candidatesToCSV(candidates);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `apply-codes-candidates-${formatDateForFile()}.csv`;
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy candidates to clipboard as tab-separated values.
 * @param {Object[]} candidates
 * @returns {Promise<boolean>}
 */
async function copyToClipboard(candidates) {
  try {
    const tsv = candidatesToTSV(candidates);
    await navigator.clipboard.writeText(tsv);
    return true;
  } catch (err) {
    console.error('[Apply Codes] Clipboard copy failed:', err);
    return false;
  }
}

/**
 * Copy shareable summary to clipboard.
 * @param {Object[]} candidates
 * @param {string} [criteria]
 * @returns {Promise<boolean>}
 */
async function shareToClipboard(candidates, criteria) {
  try {
    const text = candidatesToShareableText(candidates, criteria);
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('[Apply Codes] Share copy failed:', err);
    return false;
  }
}

// ============ HELPERS ============

function escapeCSV(str) {
  if (!str) return '';
  let s = String(str);
  // Guard against CSV formula injection
  if (/^[=+\-@\t\r]/.test(s)) {
    s = "'" + s;
  }
  if (s.includes(',') || s.includes('"') || s.includes('\n') || s.includes('\r')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function formatDate(isoString) {
  if (!isoString) return '';
  try {
    return new Date(isoString).toLocaleDateString();
  } catch {
    return isoString;
  }
}

function formatDateForFile() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

// Export
if (typeof window !== 'undefined') {
  window.ApplyCodesExport = {
    candidatesToCSV,
    candidatesToTSV,
    candidatesToShareableText,
    downloadCSV,
    copyToClipboard,
    shareToClipboard,
  };
}
